name: autotests

on: [push, pull_request]

jobs:
  autotests:
    runs-on: ubuntu-latest
    container: python:${{ matrix.python }}
    strategy:
      matrix:
        python: [3.8, 3.9, 3.10, 3.11]
        rabbitmq:
          - 3.10-management
          - 3.11-management
          - 3.12-management
    services:
      rabbitmq:
        image: rabbitmq:${{ matrix.rabbitmq }}
        ports:
          - 5672:5672
          - 15672:5672

    steps:
    - uses: actions/checkout@v3
    - name: Install utils
      run: |
        apt-get update && apt-get install -y wait-for-it

    - name: Install poetry
      run: |
        pip install poetry==1.6.1

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run autotests
      run: |
        wait-for-it rabbitmq:5672 -t 60
        poetry run coverage run --source=rabbitmq_admin -m unittest
        poetry run coverage report -m
      env:
        RABBITMQ_HOST: rabbitmq

  lint-check:
    runs-on: ubuntu-latest
    container: python:${{ matrix.python }}
    strategy:
      matrix:
        python: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pip install poetry==1.6.1

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run lint
        run: |
          poetry run flake8 --count
